### ISSUE TITLE
Missing files compared to original OpenWrt package?

### ISSUE THREAD

**Issue by alex9434** [moetayuko/openwrt-cloudflared#1]
Hi @MoetaYuko, thank you very much for providing an updated version of the Makefile for go to reflect the modifications by cloudlfare. However, I would like to use this to build the package from the source as part of the OpenWrt build. I wanted to add a link to your repository at the beginning of  my `feeds.conf.default`
`src-git golangmod https://github.com/MoetaYuko/openwrt-cloudflared.git`
to use your version for the build. Is that possible? 

I have two questions regarding this:
1. Based on your assessment, would this have a negative impact on other packages that are build with Golang (e.g. containerd)?
2. I have noticed that a number of files are not included in your package that are in the original OpenWrt page (golang-compiler.mk, golang-host-build.mk, golang-package.mk, golang-values.mk etc.). Are these packages required for full functionality? If so, could you add them to your repository so that I can use it in my `feeds.conf.default`?

**Comment by moetayuko** [comment]
> Hi @MoetaYuko, thank you very much for providing an updated version of the Makefile for go to reflect the modifications by cloudlfare. However, I would like to use this to build the package from the source as part of the OpenWrt build. I wanted to add a link to your repository at the beginning of my `feeds.conf.default` `src-git golangmod https://github.com/MoetaYuko/openwrt-cloudflared.git` to use your version for the build. Is that possible?

sure
> 
> I have two questions regarding this:
> 
>     1. Based on your assessment, would this have a negative impact on other packages that are build with Golang (e.g. contained)?

any golang packages will be built by this modified toolchain, they may continue to work but I don't think it's a good idea to do so
> 
>     2. I have noticed that a number of files are not included in your package that are in the original OpenWrt page (golang-compiler.mk, golang-host-build.mk, golang-package.mk, golang-values.mk etc.). Are these packages required for full functionality? If so, could you add them to your repository so that I can use it in my `feeds.conf.default`?

the official ones will be used, there's no need to place a copy here

**Comment by alex9434** [comment]
Hi @MoetaYuko, thank you for your quick reply.
> 
> any golang packages will be built by this modified toolchain, they may continue to work but I don't think it's a good idea to do so
> 

I understand. Would it be possible to rename your packe (e.g. rename to golang-mod) and have a modified Makefile for cloudflared to use golang-mod while all other packages continue to use the original golang?

**Comment by moetayuko** [comment]
> Hi @MoetaYuko, thank you for your quick reply.
> 
> > any golang packages will be built by this modified toolchain, they may continue to work but I don't think it's a good idea to do so
> 
> I understand. Would it be possible to rename your packe (e.g. rename to golang-mod) and have a modified Makefile for cloudflared to use golang-mod while all other packages continue to use the original golang?

Technically "possible", but obviously not supported by the current openwrt build system.

**Comment by alex9434** [comment]
Ah OK, thanks. Would it be possible to integrate the entire toolchain into the Makefile for cloudflard so that there are no dependencies?

**Comment by moetayuko** [comment]
> Ah OK, thanks. Would it be possible to integrate the entire toolchain into the Makefile for cloudflard so that there are no dependencies?

maybe, it's out of my scope.

**Comment by alex9434** [comment]
> > Ah OK, thanks. Would it be possible to integrate the entire toolchain into the Makefile for cloudflard so that there are no dependencies?
> 
> maybe, it's out of my scope.

I understand. Thank you for the quick replies and your work on this!
